### ISSUE TITLE
Shapefile imports excluding some records silently 

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#421] opened 2020-09-03 02:05 UTC

**Comment by rrowlands** [comment] 2020-09-03 21:28
This was caused by a bug in geotools.

1. I will commit a fix for this geotools bug by updating from version 16.1 to 19.4.
2. This does NOT put us on the latest version of JTS. This is the last version of geotools which is still using the "com.vividsolutions" JTS package scheme.
3. We cannot currently upgrade to the latest version of JTS (which is using the org.locationtech packages) because orientdb-spatial does not support the org.locationtech flavour of JTS.

**Comment by armageddon** [comment] 2020-09-04 16:57
Hi @rrowlands was it related to a limit of 1001 values in a list or something like that?

**Comment by justinlewis** [comment] 2020-09-25 17:42
@armageddon No, the sort function in JTS (3rd party lib) had a bug. Upgrading JTS allowed us to incorporate the fix.

**Closed** 2020-11-09 18:11 UTC
Labels: bug, data import
