### ISSUE TITLE
Unspecified error when trying to submit change request as RC from published list

### ISSUE THREAD

**Issue by dtreatman** [terraframe/geoprism-registry#188] opened 2020-04-23 23:18 UTC
Tried to add a new version of a name for a health facility on STG by navigating through the "Published" list and received this error

![image.png](https://images.zenhubusercontent.com/5dfcfd403da7a2fba63fee9a/056dfd4d-d39e-48e3-b49c-4e5da6a862e5)

**Comment by jsmethie** [comment] 2020-07-28 22:45
Duplicate of #233

**Closed by jsmethie** 2020-07-28 22:45 UTC
Labels: bug
