### ISSUE TITLE
Exported shapefiles do not have localization and have codes as the display labels

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#621] opened 2021-05-24 16:42 UTC
**List the CGR information**
- CGR version: v14.8
- CGR instance (e.g. a URL): Laos

**Describe the bug (clear and concise)**
When a user exports a shapefile, the exported shapefile:
- [x] Does not have localized names (e.g. Laos names appear with ???)
- [ ] Has CGR codes as the column headings 
- [x] File name does not include time validity for the shape file

**To Reproduce**
1. As a RM/RA: Go to a published Laos list and export the shapefile
2. Click on the shapefile
3. See errors:
* Laos characters appear as ???
* Column headings use the CGR codes (rather than display labels)
* File name only captures the geo-object name

**Expected behavior (clear and concise)**
* Any locally translated text appears instead of ???
* Column headings use the display labels (including the localized labels where appropriate)
* File name includes the timestamp for validity

**Screenshots**
![MicrosoftTeams-image (3).png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/c4327d1d-cbee-4b4e-860c-91112a730cae)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Additional context (if any)**

**Comment by rrowlands** [comment] 2021-06-03 18:16
The maximum length of a column name in a shapefile is ten characters, [and it is a hard requirement of the shapefile format which cannot be bypassed.](https://gis.stackexchange.com/questions/15784/bypassing-10-character-limit-of-field-name-in-shapefiles) Due to this requirement, if the display label is used as the column name, I would argue that the resultant shapefile is actually less understandable than it would otherwise be if the code is used (see screenshot).

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/830ed042-ca9d-4e64-a04e-46b699710fd2)

As you can see, the additional information, which would have disambiguated all the parent columns is completely removed and all you're left with is "Country (A", "Country (A_1", "Country (A_2".

For this reason I cannot recommend using the display label as a column name for shapefiles.

**Comment by vrajasekaran18** [comment] 2021-06-04 13:31
@rrowlands thanks for the input and shame about the limit on characters. Is there somewhere we can have the mapping of the code to the display labels? So that as a user I am able to make sense of the titles?

**Comment by SteeveEbener** [comment] 2021-06-05 01:41
Linked to tickets #323 and #628 => we should change the practice across the whole platform not only during the export.

The only thing though is that we would then also need to find a solution for the user to be able to link the code with the label in the lists view.

**Comment by justinlewis** [comment] 2021-06-11 17:33
Related for exports: [#628](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/628)

**Comment by justinlewis** [comment] 2021-06-11 17:39
I talked with @vrajasekaran18 about this and the plan to use codes for exported column headers is the preferred direction. A header description will be required in the exported metadata so that people can be sure how shapefile columns map to CGR attributes.

@steeveebener - Regarding your last comment here this ticket is only focusing on the exported shapefile. We should talk about changing this across other parts of the app outside this ticket to keep this one concise.

**Comment by SteeveEbener** [comment] 2021-06-14 09:11
Regarding the first point, this is the information meant to go in the data dictionary tab of the metadata spreadsheet to be exported with the shape file (see the current data dictionary tab when exporting a list in a spreadsheet)

On the second point, I understand your view but we also need to ensure consistency across the platform. Why would the headers in he shapefile for example be different from the header in the exported list (spreadsheet)? 

The broader ticket you are talking about might be #323 which is open since June 2020 => we need to look into the issue down to the geo-object type definition.

**Comment by justinlewis** [comment] 2021-06-15 15:30
@steeveebener - We need a solution for Shapefiles because they have a 12 character max limit where spreadsheets have a much larger limit making it much less of a concern. Ultimately if we use the display label for Shapefiles the app will need to truncate column headers and achieve uniqueness by appending text like "_1, _2" to the display label. Using codes reduces the likelihood of needing to append text to create uniqueness because in general a code is unique and concise. We could replicate this column naming convention in spreadsheets as well if it's decided that would be the better approach. 

I wasn't referring to that ticket. I meant it would be better to discuss outside of tickets (on a call) to make sure this is understood since changing the column names in the app UI would be a big change for the user experience.

**Comment by SteeveEbener** [comment] 2021-06-15 23:23
@justinlewis. There is no doubt that the use the "code" as the label for the headers in the shape file attribute table is the solution.

This will nevertheless means that you will very soon have to address:
1. The question of the metadata to be attached to the shape file (ticket #628) 
2. The inconsistency this will generates with the headers used in the lists (ticket #323)
3. The need to allow the user to edit the "code" for the "fixed" attributes at the geo-object level (ticket #323)

=> The call should cover all these points and hopefully allow us to address all of them at once

From my point of view, the current long labels used as headers in the lists are really not practical. To be honest, I look at the information in the cells to identify the column I am looking for, initial reason for submitting #323

**Comment by vrajasekaran18** [comment] 2021-09-06 09:29
@justinlewis did the fix for Lao characters appearing as ??? make it in 14.9? Rica's recently tested the fix and the Lao characters now appear in a strange font (picture below)
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/df063f50-119e-4b7c-a445-49bc3b0d88a3)

**Comment by rrowlands** [comment] 2021-09-29 20:26
The actual spreadsheet is being written as UTF-8. [This fix was included in 0.14.9.](https://github.com/terraframe/geoprism-registry/commit/62add4125fc46b20667a8cb1ed8c259bc015ed7d#diff-c9bd3b175cdbdb6bd50098ea57173d8060f0ec9b68818b22f31f6f88123fe432)

What I think is actually happening is what is described in #671. The shapefile is correctly written as UTF-8, however your client is not properly reading it as UTF-8. The fix, as described in that ticket, is to include a '.cpg' file inside the Shapefile.

Since that issue can be considered a duplicate of #671, I am considering this ticket closed.

**Closed by rrowlands** 2021-09-29 20:26 UTC
Labels: bug, data export, needs user validation
