### ISSUE TITLE
Error deleting Geo-Object Type that is participating in a "unknown" hierarchy

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#476] opened 2020-12-01 21:51 UTC
**List the CGR information**
- CGR version: 0.12.2
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
This ticket is derived from an issue that came up when testing ticket [#436](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/436).

From @steeveebener:

Just tested that in staging and:

deleting the list: OK
removing the GeoObject type from the hierarchies: Ok
Deleting the GeoObject type: Ok
But when trying to directly deleting the GeoObject type I get the following message while I could not find any hierarchies containing the GeoObject type in question (Village (NMCP) under the MOH in this case):
![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/6c2529b8-e795-4617-bcc2-e39f6fba1818)

=> Could there be an error in the message, meaning that it should make reference to the fact that GeoObject Type is being used in at least one list? (the error message making reference to the hierarchy should maybe also make reference to "at least one hierarchy")

**To Reproduce**
1. As a .....[role]: Go to 
2. Click on 
3. See error

**Expected behavior (clear and concise)**
- To be able to delete Geo-Object Types that are not participating in a hierarchy and that have not had instance data (Geo-Objects) uploaded to them.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**

**Comment by SteeveEbener** [comment] 2020-12-04 01:37
Can't reproduce this neither now that we have implemented the Tolkien data in staging. 

We can close this ticket. We will re-open it in case the error appears again

**Closed** 2020-12-04 03:06 UTC
Labels: bug
