### ISSUE TITLE
An unspecified occurs when an RM tries to submit a geometry edit for a geo-object using the marker tool

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#579] opened 2021-03-19 10:32 UTC
**List the CGR information**
- CGR version: v0.14.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
An RM tries to edit the geometry (point geometry) of a referral hospital using the marker tool, when the RM tries to submit the edit the user gets an unspecified error has occurred message.

**To Reproduce**
1. As a RM Go to edit a geo-object from the list view (used a referral hospital)
2. Click on edit geometries
3. Add a new instance
4. Click edit geometries for the new instance
5. Use the marker tool to select a new location on the map for the geo-object
6. Click submit to save the geometry and submit to submit the edit
7. See error: An unspecified error has occurred. Please try your operation again. If the problem continues, alert your technical support staff.
3. See error

**Expected behavior (clear and concise)**
The edit of a geometry using the marker tool saves successfully.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/2ed9a9d6-cbee-4a1f-a530-34668268b6c5)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:

**Additional context (if any)**

**Comment by rrowlands** [comment] 2021-03-22 21:47
I have identified two separate bugs which could have caused the described issue.

1. The first bug happens when a user submits a version without a geometry. This can be reproduced by creating a new version, setting the dates and then submitting (without any geometry editing). This bug has been fixed (and was caused by a quirk in our OrientDB client java adapter).

2. The second bug happens when the user edits geometry on a Geo-Object Type which has an unsupported geometry type. You can tell if the Geo-Object Type has an unsupported geometry type by editing the Geo-Object Type in the hierarchy manager. If there is no option in the dropdown for "geometry type" (as shown in the screenshot below), then the Geo-Object Type needs to be rebuilt and the data stored within is invalid.

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/6932091c-d1b7-43a9-9476-6ad77996dddd)

This second bug cannot be fixed without deleting and re-creating the Geo-Object Type with a proper geometry type value. I am told by @justinlewis that the Tolkein demo data is currently in the process of being rebuilt and so we will wait for this issue to be resolved until after the data is rebuilt.

**Comment by justinlewis** [comment] 2021-06-21 17:48
Closing because this area of the code has changed a lot since the ticket was created. This functionality will be tested in the upcoming release.

**Closed** 2021-06-21 17:48 UTC
Labels: bug
