### ISSUE TITLE
Added geo-object with only the unique ID being specified not appearing in the list

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#721] opened 2022-01-04 06:21 UTC
**List the CGR information**
- CGR version: 0.17.2
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
it is possible to add a geo-object by only specifying its unique ID but, once done, the geo-object does not appear in the list while it is in the graph

**To Reproduce**
As a RA/RM:
1. Go to the lists module
2. Open the list for a geo-object type over which the RA/RM has the  curation mandate
3. Click the "Add geo-object" button
4. Specify the existence period and then only an available unique ID (no other attribute)
5. Click the "Submit" button (the window confirming the submission appears)
6. Go back to the list and refresh it
7. See the error: the added geo-object is not appearing
8. Click the "Add Geo-Object" button once again and try to add a new geo-object using the same unique identifier => an error message indicating that the ID is already attributed appears). The geo-object is in the graph

If you repeat the same process as above but this time you include the Geo-Object name them the new geo-object will appear in the list

**Expected behavior (clear and concise)**
The added geo-object appears in the list even if only the unique identifier has been specified

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: The latest version

**Additional context (if any)**

**Comment by jsmethie** [comment] 2022-04-14 21:28
Duplicate of #735

**Closed** 2022-04-14 21:28 UTC
Labels: bug, duplicate
