### ISSUE TITLE
Modules the SRA should have access to

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#248] opened 2020-05-21 21:46 UTC
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
Some of the modules that the SRA should have access to are not appearing on the home page but accessible from the burger menu while others he should not access are in the home page and/or in the burger menu 

**To Reproduce**
As a SRA
1. Log in
2. See error: accessibility to some module (see list of those he should access in the expected behavior section.

**Expected behavior (clear and concise)**
Because the SRA is linked to the cross sectoral governance mechanism, he should:

- have access to the following modules without editing rights from the home page: lists, explorer (accessible from the burger menu though)
- NOT have access to the import, change request, scheduled jobs and tasks modules (also accessible from the burger)

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/82609602-66a80d80-9bef-11ea-96c9-165cbbeb4715.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context (if any)**
This issue relates to the management of user roles

**Comment by justinlewis** [comment] 2020-05-26 17:16
Duplicate of: https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/171

**Comment by SteeveEbener** [comment] 2020-05-26 20:55
Hi Justin,

This is not a complete duplicate as my post makes reference to modules that the SRA should not have access to, including in the burger

**Comment by rrowlands** [comment] 2020-06-04 20:31
Since this ticket is a duplicate, I'm closing it. We can address the issues in #171.

**Closed by rrowlands** 2020-06-04 20:31 UTC
Labels: bug, duplicate, user roles
