### ISSUE TITLE
Importing shapefile to Geo-Object Type with existing data creating sliced attribute time versions

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#568] opened 2021-03-13 01:42 UTC
Reported by @steeveebener 
  
Here is a summary of what I have done and when the unnecessary instances appeared for a given level (Provinces):  
1.     Imported the list (spreadsheet) of Provinces with the temporal validity 01.01.200 – 09.03.2021 => No problem  
2.     Added the new Province of Orrostar starting from 20.04.2007 => No problem  
3.     Imported the geometry for the 01.01.200-19.04.2007 period from a first shape file (update only option, indicated hierarchy and the attribute containing the code and name but not the parent) => No problem  
4.     Imported the geometry for the 20.04.2007-09.03.2021 from a second shape file (update only option, indicated hierarchy and the attribute containing the code and name but not the parent) => then the unnecessary instances appear at the Province level and this across all the geo-objects ![](https://a.slack-edge.com/production-standard-emoji-assets/13.0/google-medium/1f60a@2x.png)You can see that by looking at the master list of Provinces in Production.I did not upload the geometry for the lower levels (County and Shire) for the moment but I am sure the same would happen.

**Comment by rrowlands** [comment] 2021-03-15 19:13
Here's what I see can be improved based on this ticket:

1. Don't create a new version for an attribute if the value has not been explicitly set by the user during import. This is especially relevant for updates: always setting the status attribute to "active" makes sense if the Geo-Object is new. It does not make sense if we're updating an existing one.
2. There's no need to create a new version for an attribute if there are no gaps on between the end date of the previous version and the start date of the new version.

Let me know if I missed anything...

You mentioned during our phone call that perhaps the importer was updating (or creating?) other objects that it should not have been. Is this still happening? I don't see anything about this in the description of this ticket.

**Comment by SteeveEbener** [comment] 2021-03-17 00:58
Sorry for the late feedback.

I am not sure that what you have done is solving the issue. Quite some testing will be needed to confirm it and make sure this is not creating other problems and/or complexities.

Few questions regarding the rules you have implemented:
- Rule 1: Do you mean that an empty cell in the imported file is now meaning "don't update the value already in the graph"? This could be problematic this is the case. What if I want to "empty" the content of a specific set of cells?  I also see a problem on the side of the user who would have to check cell by cell what is in the spreadsheet he is importing
- Rule 2: This does not solve the case where the current value is set for the 01.01.2001-01.01.2005 period and what the file I import contains the same value for the 01.01.2004-01.01.2010 period
- Rule 3: Does the backend not need both the unique ID and the display label attributes to perform the matching? 

Apart from that, I was actually wondering why this problem only happens when I was importing a shape file and not when importing a spreadsheet and I think that I found the reason:
- For spreadsheets, I was first inactivating the admin units that were stopping to exist from a given date and then only importing the new admin unit
- For shapefiles, the admin units were already inactivated through the list but I was then uploading the complete shapefile (whole country) instead of a shapefile containing only the new admin units

Your specific question refers to bullet point 4 in the original ticket posted by Justin. I will have to test this again in the new release to see if the problem is still there

**Comment by SteeveEbener** [comment] 2021-03-17 01:23
I am still wondering if it would actually not be possible to implement one generic succession of rules that could apply to all the attributes (including geometry) instead of a set of "disconnected" rules . 

What comes to my mind is as follow and would need to be applied attribute by attribute during the import: 
1. Is the temporal validy of the value that is imported overlaps with the temporal validity of the value already in the graph or is in direct temporal continuity with such information (no temporal gaps)
  1.1 If No, create a new instance for that attribute with the value that is being imported
  1.2 If yes, check if the value for that attribute is the same between the imported file and the graph:
      1.2.1 If yes, do not create a new instance for that attribute but expand its temporal validity accordingly
      1.2.2 If no, create a new instance for that attribute with the new value associated to it from the imported file

**Comment by rrowlands** [comment] 2021-03-17 22:05
The rules that I mentioned above apply to all attributes.

1. No, when I say "explicitly set by the user during import", I am talking about the import configuration, not the setting of a value in the spreadsheet. If you have mapped an attribute to a column in the spreadsheet during import configuration, and the spreadsheet does not contain a value in that cell, and the "copy blank values" checkbox is checked, the existing expected behaviour will continue as expected.
2. Correct. My changes did not account for that use-case. I will discuss this with the team.
3. The back-end only matches on code for the child. Label / synonym based matching only happens when finding the parent.

**Comment by SteeveEbener** [comment] 2021-03-26 23:24
Hi Richard,

1. Just to make sure, when you keep the "Copy blank value" option checked empty cells from the imported spreadsheet do overwrite the corresponding values that are in the graph?
3. Sorry but I did not get it. What happens if in the attribute matching window you don't specify the field containing the display label and then in the hierarchy matching window you select the "code, label and synonyms" option?

Thanks in advance for your answer

**Comment by rrowlands** [comment] 2021-04-13 15:32
1. Yes that is correct.
2. The "code, label and synonyms" option refers to the parent, not the child. When that value is selected, it matches the column in the spreadsheet containing a **parent** value which you are then attempting to match based on the code, label or synonym of the parent. The display label field you're talking about is for the child only.

**Comment by SteeveEbener** [comment] 2021-06-05 00:28
@rrowlands : Sorry for the late reply on this.

Thanks for your answer in the previous message here.

The result of the "Copy blank value" option  should be made more explicit to the user to avoid any unexpected results

Thanks for the explanation for the second point. What we should then maybe do is have the "Hierarchy" field at the bottom of the list in the attribute matching window or maybe even in the hierarchy matching window to avoid the confusion

**Comment by rrowlands** [comment] 2021-06-08 16:29
> The result of the "Copy blank value" option should be made more explicit to the user to avoid any unexpected results

Do you have any suggestions as to how to achieve this goal? I struggle to think of a change here partially because I'm not sure that I fully understand the source of the confusion.

> What we should then maybe do is have the "Hierarchy" field at the bottom of the list in the attribute matching window or maybe even in the hierarchy matching window to avoid the confusion

This is an interesting suggestion. I have also had the idea to move the hierarchy field to the original import page (where the file is selected). This would also help with narrowing the results of the GeoObjectType dropdown, which could be advantageous.

**Comment by SteeveEbener** [comment] 2021-06-14 08:46
On the first issue, what about replacing "Copy blank value" with "Import blank cells"?

Both options regarding where to place the field asking for the hierarchy are fine with me.

**Comment by SteeveEbener** [comment] 2021-06-18 13:14
Checked on 0.14.10:
- "Copy blank value" has not been replaced by "Import blank cells"?
- The Hierarchy selection field is still in the "Attribute Matching" window

**Comment by rrowlands** [comment] 2021-06-21 18:21
Adding the release 0.14.10 tag to this was a mistake. There were no changes on this ticket included in that release.

**Comment by SteeveEbener** [comment] 2021-08-29 02:33
Just tested under 0.15.2 and the split is still happening

**Comment by rrowlands** [comment] 2022-12-21 23:22
[Nine different unit tests](https://github.com/terraframe/geoprism-registry/blob/master/georegistry-test/src/test/java/net/geoprism/registry/service/ValueOverTimeTest.java) were implemented as part of 3a221eef40b2168303a46ae110c68ee87715b1e1, so to simply say "it still doesn't work" is insufficient. We must document exactly which use-cases are not working. Something along the lines of, for example:

"I thought the system should do this and it doesn't :"

Existing:
[ start: 2020-04-04, end: 2021-04-04, value: 13 ]

Imported:
[ start: 2020-07-04, end: 2021-01-04, value: 16 ]

Expected Outcome:
[ start: 2020-04-04, end: 2020-07-03, value: 13 ]
[ start: 2020-07-04, end: 2021-01-04, value: 16 ]
[ start: 2021-01-05, end: 2021-04-04, value: 13 ]

*Note that as far as I know the above use-case actually does work and is provided for example/template only.

My goal here is not to burden you with defining all permutation of possible usecases, one or two should suffice.

**Comment by SteeveEbener** [comment] 2023-01-06 12:38
This issue has not appeared again since the new design.

Proposing we close this ticket. It can always be re-opened in case the issue occurs again.

**Closed** 2023-02-27 18:31 UTC
Labels: bug, migrate/status-pendingfeedback
