### ISSUE TITLE
Importer: Null Pointer RowValidationProblem discovered by Steve

### ISSUE THREAD

**Issue by rrowlands** [terraframe/geoprism-registry#509] opened 2021-01-08 17:49 UTC
RowValidationProblem on import.  This is what Steeve said the steps where
[8:21 PM] Difficult to reproduce but you can see the error message in question  in staging if you:
1. Log in as the MOH RA
2. go to the Scheduled Jobs module
3. Click the "resolve problems" button for the Health_Centre_ML_01012000.xlsx import
4. See the message in the Problem Type cell
The screenshot he references points to a null pointer exception

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/b0314df3-44d9-4811-84c4-dbdda54a17c7)

**Comment by rrowlands** [comment] 2021-01-08 18:33
I am attempting to reimport this file (so that I can find the root cause of the issue), and I am encountering an error. The import is referencing a hierarchy (GROUP_HF) which no longer exists.

**Comment by justinlewis** [comment] 2021-01-08 18:51
@steeveebener Since you originally reported this do you know why the hierarchy was deleted and/or are you able to reproduce the issue?

**Comment by SteeveEbener** [comment] 2021-01-09 02:08
@justinlewis . I don't know who deleted the hierarchy but it is not me...I will then try to re-create the whole thing hoping that nobody will delete it this time....

**Comment by SteeveEbener** [comment] 2021-01-09 02:24
The HF_GROUP (I don't have it under GROUP_HF) hierarchy is still there (Label: Health facilities) with two geo-object types attached to it: Health Center (group) and Health Posts (group).

I just tried to re-upload the file I shared for the health center (group) geo-object type and the error message I get is "An unspecified error has occurred. Please contact your technical support team. Your import contained problems which must be resolved by fixing and re-uploading the source data."

**Comment by rrowlands** [comment] 2021-01-15 16:29
Spreadsheet which originally caused the error:

[https://app.zenhub.com/files/142912671/b0b163fa-ced1-44ea-b0c4-81df596965c6/download](https://app.zenhub.com/files/142912671/b0b163fa-ced1-44ea-b0c4-81df596965c6/download)

**Comment by SteeveEbener** [comment] 2021-01-31 08:10
I have re-created the group and re-imported the file against the Group Health Centers geo-object type. The message is not the same anymore in the job details. Here is the new one:
![image](https://user-images.githubusercontent.com/12602163/106378245-2899f500-63de-11eb-91e5-a6c10ec59684.png)

=> is this the new message for the same error initially posted here or is it another issue? If yes, few things:

1. Not being able to import geo-object presenting the same unique ID as other geo-objects for another geo-object type is going to be a problem at some point as it is very much likely that different sectors using the same coding scheme for different geo-object types
2. The first sentence of the message is anyway not explicit "A Geo-Object with the code [HF0068] already exists with Geo-Object Type [Group Health Centers]" as the geo-object type against which I am doing the import is "Group Health Centers" => maybe that what you meant is "A Geo-Object with the code [HF0068] already exists among other geo-object types"

**Comment by justinlewis** [comment] 2021-02-09 21:32
@steeveebener your first point should be talked about outside this ticket as that is a big item that is separate from the UI show "RowValidationProblem".  

We can work on the second point in Sprint 14. I'll move the ticket to that sprint.

**Comment by SteeveEbener** [comment] 2021-02-23 08:04
@justinlewis I was testing the first point to capture it in a new ticket when I found out that  I can now create a new geo- object using an already attributed unique ID (code) ...and this for the  same geo-object type (see the first two lines) or across different types (SC0008 is the unique ID for a school in the Tolkien dataset):
![image](https://user-images.githubusercontent.com/12602163/108816001-58f53d80-75f0-11eb-94a5-80d54c39dd48.png)

=> did you change anything since Feb 10? is this a new bug?

**Comment by justinlewis** [comment] 2021-03-02 22:44
@steevebener Your last comment should be a new ticket. I think it's becasue the second one with the "test" label has white spaces before the first real character '	HF0002'. If I'm correct they are different codes but we need to make sure to not capture white space. Let me know if you want me to create a ticket.

**Comment by SteeveEbener** [comment] 2021-03-05 01:46
@justinlewis. I did not notice the space in front of the code (don't know where they came from actually as there are several of them for the record with the "test" label. I just created a new record with only one space in from of the "HF0002" part and it created a new record as well => Thanks in advance for creating a new ticket for that issue

Coming back to the issue of the original ticket it is now clear after talking with Nate that the CGR is not yet able to manage for different geo-objects of different types (schools, health facilities,...) to have the same unique ID => this is indeed an issue to be addressed separately and which relates to the possibility to handle upgrades => I will create a new ticket for us to be able to start working on this as part of rules that needs to be in place to capture historic changes.

**Comment by justinlewis** [comment] 2021-03-11 19:08
Created [Ticket 566](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/566) for the white space issue

**Comment by rrowlands** [comment] 2021-03-17 22:19
@SteeveEbener Addressing your point #2 above: The Geo-Object Type in the error message is supposed to be that of the existing Geo-Object in the system which is conflicting. Not the one being imported. If I were to change this to be the case, would that be acceptable?

**Comment by SteeveEbener** [comment] 2021-03-23 08:05
@rrowlands : Do you mean to change this in the error message? If yes, what would be the content of the proposed new message?

**Comment by rrowlands** [comment] 2021-03-24 15:25
The error message would be the same, however the Geo-Object Type in the message would be that of the conflicting one. Not the one which is attempting to be created.

**Comment by SteeveEbener** [comment] 2021-03-26 23:30
To make sure, if the code is already used by a health center while you are uploading health posts for example, the error message would then read:

"A Geo-Object with the code [HF0068] already exists with Geo-Object type [Health Center]. Geo-Object codes are globally unique. Please choose a different value"

Is that correct?

**Comment by rrowlands** [comment] 2021-04-13 15:35
Yes that is correct.

**Comment by SteeveEbener** [comment] 2021-04-13 23:22
Sounds good. Thanks

**Comment by rrowlands** [comment] 2021-10-08 21:03
I have added the correct GeoObjectType label to the DuplicateGeoObjectCodeException.

**Closed** 2021-11-22 17:03 UTC
Labels: bug
