### ISSUE TITLE
List creation throws an error - Cannot Create a list

### ISSUE THREAD

**Issue by armageddon** [terraframe/geoprism-registry#464] opened 2020-11-23 20:20 UTC
**List the CGR information**
- CGR version: Version: 0.11.1
- https://demo-georegistry.geoprism.net:8443/cgr/manage#/registry/master-lists

**Describe the bug (clear and concise)**
Where trying to create a list as per the CGR User Guide, an error is displayed when trying to submit, and the list is not created

**To Reproduce**
1. As a RM
2. Click on Lists
3. Click on Create for 'Ministry of Health' organisation
4. Label = testlist1
5. GeoObjectType = Health Post
6. Code = code_testlist
7. Visibilty = Public
8. Master List = false
9. National Hospital, Referral Hospital, Health Centre, Shire all checked
10.Click 'Submit' 
11. An error is displayed 'An object already exists that has values on attributes that are unique.'

**Expected behavior (clear and concise)**
List should be created

**Screenshots**
![image](https://user-images.githubusercontent.com/114864/100010937-b1daed00-2dd9-11eb-8cb5-e927f81164bc.png)

**Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Browser: Chrome
 - Version: Version 87.0.4280.67 (Official Build) (x86_64)

**Additional context (if any)**

**Comment by jsmethie** [comment] 2020-12-03 18:13
This message is thrown when the user is trying to create a new list where the "Is Master" flag is set to true, when another list already exists with the "Is Master" equal to true for that give type.  The expected behavior is that only one list per type can be set to "Is Master" equal to true.  So the system is behaving as expected.

I will update the message to give something more specific.

**Comment by CarlyNel** [comment] 2020-12-29 13:20
Pierre to review TF's above feedback, test against the expected behaviour for Master Lists, and then close this ticket once satisfied.

**Comment by justinlewis** [comment] 2021-02-09 20:21
Closing because of inactivity

**Closed by justinlewis** 2021-02-09 20:21 UTC
Labels: bug, lists, wontfix
