### ISSUE TITLE
As a RC, I get an error message when submitting a change request from the list but the request goes through when using the change request manager

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#233] opened 2020-05-11 07:36 UTC
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
I tried to first submit a change request from the list but it did not work (I got the error message included in the screenshot).

I then tried from the change request module and the request went through

**To Reproduce**
As the RC for a Given GeoObject type over which it has the RC role:
1. Try to submit a change request from the list
2. See the error message included below
3. Try to submit the same change request from the change request manager and see it going through

**Expected behavior (clear and concise)**
The change request can go be submitted through both the list and the change request manager.

Just one caveats: it would be good if, in this case, the icon appearing in the list for the RC to submit a change request was not an editing pen (See suggestion in the screenshots below). This could also be used as the image for the change request module 

**Screenshots**
Error message appearing when submitting the change from the list
![image](https://user-images.githubusercontent.com/12602163/81534809-3cf31900-939b-11ea-956e-7482c17ea6f2.png)

Suggested icon to replace the pen when it is a change request and not an edit:
![image](https://user-images.githubusercontent.com/12602163/81535644-c0613a00-939c-11ea-85b3-150ba5b1fa53.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by jsmethie** [comment] 2020-07-28 21:45
I can not recreate this error.  Can you give me some more detail on what specific master list you used to submit the change request? Also what type of changes you made in the change request?

**Comment by SteeveEbener** [comment] 2020-07-29 02:36
Hi Justin. did you try the process mentioned by Derek in ticket #188: Tried to add a new version of a name for a health facility on STG by navigating through the "Published" list and received this error

**Comment by CarlyNel** [comment] 2020-07-29 15:04
Hi both, not sure if these are related but I've come across the same looking error elsewhere so adding them here in case helpful/relevant. Ticket [#354](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/354) and [#339](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/339).

If not, feel free to ignore.

**Comment by justinlewis** [comment] 2020-08-20 16:03
Closing because we can't reproduce.  If you can reproduce this please give us the steps listed above in more detail including the list you where adding the object from and all the settings in the modal before submission. We can re-open this ticket if you can reproduce and provide this info.

**Closed by justinlewis** 2020-08-20 16:03 UTC
Labels: bug, change requests
