### ISSUE TITLE
Role appearing several times in the header when the RM or RC is in charge of several GeObject types

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#208] opened 2020-05-02 03:39 UTC
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The role of the user (RM or RC in this case) is appearing several times when the user is put in charge of several GeoObject types (number of GeoObject types = number of appearances)

**To Reproduce**
As a RA:
1. Create several GeoObject types
2 Create a RM or RC account and attach the GeoObject types created under point 1 to this RM or RC
3. Log out

As the RM or RC that has just been created:
1. Log in 
2. See error: the role of RM is appearing several times in the header

**Expected behavior (clear and concise)**
The role is appearing only once in the header 

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/80854236-044f9300-8c69-11ea-87f1-a5e9d543fbf3.png)

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment] 2020-06-06 22:57
I propose we remove the display of roles from the header display because it could get very large for users who are assigned to many types. This made sense when the roles where more simple in the past but now I feel there is diminishing value as the labels will need to be long to make them meaningful. For example these are the type of labels we might need now. 

- Regisrty Maintainer (Cambodia), Registry Maintainer (Province), Registry Contributor (Commune)....

**Comment by SteeveEbener** [comment] 2020-06-07 03:33
Now that we have agreed that roles can't cross organizations under the same user account the next fundamental question here is: can a user have different roles on different GeoObject Types within the same organization?

In other words can the RC for communes actually be the RM for provinces in the MOI as per Justin's example? I would say that the answer is yes. Example:  The RM for foci in the Malaria programme could be a RC for health facilities.

=> I think useful for the user to know which role he has on which GeoObject type(s) within its organization and while the list might be long I am in favor of keeping it. We could just continue using RM instead of Registry Maintainer and group GeoObject types by role 

=> Justin's example would become: RM (Cambodia, Province), RC (Commune)

**Comment by justinlewis** [comment] 2020-06-07 04:28
I think yes as well that a single user can have different roles for different GeoObjectTypes.

That abbreviated approach would be an improvement although given what I've seen as example hierarchies it seems a user could still end up having many roles/GeoObjectType.  We could truncate the labels after a certain number of characters to ensure they don't overflow into the logo.

**Comment by nmceachen** [comment] 2020-06-07 05:34
A user should be able to belong to more than one role within an organization. Regarding role labels: I propose removing “Registry” entirely. For example:

MOI Registry Administrator -> MOI Administrator
Health Facility Registry Maintainer -> Health Facility Maintainer
Village Registry Contributor -> Village Contributor

Super Registry Administrator -> Registry Administrator

**Comment by SteeveEbener** [comment] 2020-06-07 12:52
@nmceachen : I don't think that changing role spelling is a good idea (especially the last one that converts a SRA into an RA)  as this is confusing + this result in longer text than the solution I am proposing

**Comment by SteeveEbener** [comment] 2020-06-11 09:30
Thanks Carly,

I would go for a mix between the two options which is:

- keep the username (without the role) next to the burger menu) - Like in option 2
- access the user profile by clicking on the username - like in option 1

=> no new item in the burger menu
=> this would just require to remove the role part from the information in question. The rest being already implemented.

Just one thing though: the RA should be able to see the complete list of GeoObject types he has created (not the case from the moment) => maybe a bug to document in github

**Comment by CarlyNel** [comment] 2020-06-11 14:46
Thanks for the quick feedback Steeve - appreciate it. I have noted your bug comment and will try to recreate it for screenshots to add into GitHub for addressing.

@justinlewis as per Steeve's feedback above, could we please _only_ keep the user name that is displayed next to the burger menu, and remove any mention of associated roles that currently appear in brackets after the user name. The role details will remain visible when the user clicks on their user name (as is currently the case) to view more detailed information.

So the header should look as follows:

![image](https://user-images.githubusercontent.com/66491033/84400505-699c8980-ac02-11ea-8e0c-56b3d61d6053.png)

And when the username is clicked on, the following pop up is displayed (which is the current functionality)

![image](https://user-images.githubusercontent.com/66491033/84400859-ddd72d00-ac02-11ea-9536-472dbfe71ca6.png)

Any questions, please give a shout.

Many thanks.

**Comment by CarlyNel** [comment] 2020-06-18 21:05
I can confirm that this fix has been implemented. 

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/6a68c58e-1253-4680-8a35-3ac5dd792b33)

And associated roles remain visible.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/66c963be-663b-450f-89a2-c0576192c715)

**Closed by CarlyNel** 2020-06-18 21:05 UTC
Labels: enhancement, ui / ux, user roles
