### ISSUE TITLE
Can't define role at the level of each geo-object typr part of a group

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#634] opened 2021-06-13 09:10 UTC
**List the CGR information**
- CGR version: 14.7
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
The RM/RC role can only be define at the level of a group and not for each of the geo-object types that are part of it

**To Reproduce**

As the RA (MOH for Tolkien for example) 
2. Go to the settings module
3. Open the user account information for the MOH RM or MOH RC
4. See the issue: the role can only be attached to the Health facility group ad not each type of health facilities part of this group

**Expected behavior (clear and concise)**
The role can be attached attached for each of the geo-object types part of a group

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/121801301-453a1980-cc69-11eb-9473-26da53b36765.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: The most recent one

**Additional context (if any)**

**Comment by justinlewis** [comment] 2021-10-06 02:47
Duplicate of [#586](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/586)

**Comment by justinlewis** [comment] 2021-10-06 02:49
Closing because it's a duplicate

**Closed by justinlewis** 2021-10-06 02:49 UTC
Labels: duplicate, enhancement, needs prioritization
