### ISSUE TITLE
Marking a master list as private - status not visible

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#340] opened 2020-06-26 16:25 UTC
Instance: 
Staging - Firefox
0.8.1 on 22 June 2020

1. As a MOH-RA I created a master list and marked it as private.
2. While it is (correctly) not visible to an individual from another org, it isn’t showing to me as being a private list on the Master List home screen.

I expected to see the list that I had created contain “Private” after the title.”

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/23d55e9a-ccc8-4f70-9c06-76e90fd341f8)

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/94c758b6-96fa-4361-894c-5d7fc4ceabf4)

**Comment by SteeveEbener** [comment] 2020-06-27 00:42
Duplicate of ticket #324

**Closed** 2020-08-13 23:42 UTC
Labels: duplicate, lists, ui / ux
