### ISSUE TITLE
The use of explorer to view the geometry of a GeoObject from the lists module is slow and not always working

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#420] opened 2020-08-29 01:18 UTC
**List the CGR information**
- CGR version: 0.11.1
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
Viewing the geometry of a GeoObject using the explorer is:

1.  slow (up to 10 times slower than looking at the geometry through the editing geometry modale (editing window) 
2. not always working as expected:
- sometimes does not zoom to the GeoObject (first screenshot below)
- shows the GeoObject one level bellow (Counties) than the GeoObject itself (Province) (second screenshot below)
- The GeoObject is just not visible due to the symbology being used (third screenshot below)

**To Reproduce**
As any user
1. Go to the lists module
2. Open one of the lists for GeoObject types of the polygon contiguous form (admin divisions for example) 
3. Click on the pin icon for different GeoObjects
4. See errors listed here above

**Expected behavior (clear and concise)**
The window to view a GeoObject open rapidly, shows the correct information and this using an appropriate symbology.

**Suggestion**
1. Use a non-editable version of the editing geometry modale to visualize the geography of a given GeoObject from the lists module

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/91625130-65009980-e9d7-11ea-81d9-097afbf61d2e.png)

![image](https://user-images.githubusercontent.com/12602163/91625169-bf015f00-e9d7-11ea-944e-fc3b686ca7b0.png)

![image](https://user-images.githubusercontent.com/12602163/91625190-da6c6a00-e9d7-11ea-9c9f-e9aeb67c5e9f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: google Chrome
 - Version: 85.0.4183.83 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by CarlyNel** [comment] 2020-09-16 19:33
The above suggestion to have the Explorer not allow editing has been split into a new ticket [#429](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/429).

**Comment by SteeveEbener** [comment] 2020-09-16 22:28
@Carly this ticket does not relate to editing but to the visualization of a GeoObject from the lists module 

I don't see the need to create a new ticket to talk about editing from here. The suggestion is just referring to the use of the geometry editing modale (window) you access when you want to edit a GeoObject (see screenshot below) as the tool to also be used for visualizing a GeoObject (when you click on the location pin icon from a list).

I hope this clarifies. Please don't hesitate to let me know if this is not the case.

![image.png](https://images.zenhubusercontent.com/5e0a91f05164badb1470b68d/e17acf1b-db3d-4075-9c93-fa1dce760dd3)

**Comment by CarlyNel** [comment] 2020-09-24 13:07
Terraframe to determine the cause of the slowness before a fix can be put in place. cc @justinlewis

**Comment by apliu02** [comment] 2020-09-24 13:32
And to determine cause of #2 (data not showing up as expected)

**Comment by justinlewis** [comment] 2020-11-25 20:30
An improvement to the explorer is being worked on for Sprint 13 which may address this.

**Comment by justinlewis** [comment] 2020-12-17 19:38
Moving to In Review to test if the new redesign invalidates this.

**Comment by SteeveEbener** [comment] 2020-12-30 09:45
Just tested ve 13 under staging and here are my feedback in relation to the points listed in the original ticket:

1. Speed: Not an issue anymore
2. Zoom: Showing all the geo-objects part of the concerned type is a good thing but it would be important for the window to zoom on the geo-object of interest instead of zooming to the extent of the whole layer (might be difficult to identify the geo-object of interest when the layer cover a whole country for example
3. Symbology: It would be good if the color scheme used to differentiate the geo-object of interest from the other ones would always be the same. The scheme used for polygons is for example good (geo-object of interest = orange (would even be better if red), other geo-objects = light green) while the one used for points isn't
4. Labels: Having the label appear on top of each geo-object is also a good thing but it would be great if a way could be found to have only one label appearing on top of each polygon as having multiple labels is misleading, especially those at the border of  each polygon. Example:
![image](https://user-images.githubusercontent.com/12602163/103343126-3bab6380-4ac6-11eb-8e8f-104c9084b0ef.png)

**Comment by SteeveEbener** [comment] 2021-01-13 12:06
The point regarding the labeling issue has been removed from the ticket and placed in user feedback Nbr 67

**Comment by rrowlands** [comment] 2021-01-20 18:41
With regards to the Zoom bullet points:

1. Zooming to the Geo-Object of interest (instead of the bounding box of all displayed features) has been implemented and will be part of 0.13.2. As far as I can tell, this requirement only applies to viewing an existing Geo-Object as selected from the master-list, let me know if this assumption does not hold.
2. The easiest thing to do is to disable the animation. The map will immediately display the selected Geo-Object at the appropriate zoom level. I can also implement this behaviour when searching and clicking the (zoom to location) map icon, just let me know.
3. I have reduced the zoom level for point types by a little bit. This might require some further tweaking to get exactly how you like. Let me know if you want it adjusted further.
    Would you also like this to apply to the zoom feature when searching?

**Comment by SteeveEbener** [comment] 2021-01-31 03:49
Thanks Richard.

1. All good for the Zooming to the Geo-Object of interest.
2. The animation has been removed but the global image still appears before seeing the final zooming => Is it possible to avoid seeing the global image
3. The zoom level for point types from the list module is good now, thanks. Which zoom feature are you referring to? the one in the explorer module? If yes, then no need to change anything as there are more significant changes to be implemented in this module

**Comment by rrowlands** [comment] 2021-02-09 23:23
2. Yes but it should be placed into a new ticket because it is not easy to do and should be prioritized as such.
3. Yes I was referring to the one in the explorer.

**Closed by rrowlands** 2021-02-09 23:23 UTC
Labels: explorer

**Comment by SteeveEbener** [comment] 2021-02-09 23:36
Can you please stop closing tickets I have initiated? Thanks
