### ISSUE TITLE
Create ability for lists to be publicly available with no login required

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#493] opened 2020-12-16 15:17 UTC
Taken from [Laos feedback](https://docs.google.com/spreadsheets/d/1VD9sTHAx5CukHyjTEH9--9GjVM-oLpJmpbw1AOmFTHw/edit#gid=876136817). Context can be found on User Feedback Laos tab, row 3.

**Comment by justinlewis** [comment] 2021-03-11 19:01
Marking as duplicate of: https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/552

**Closed** 2021-03-11 19:01 UTC
Labels: country feedback, duplicate
