### ISSUE TITLE
Date picker cut off from page in Explorer search bar

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#763] opened 2022-04-11 09:51 UTC
**List the CGR information**
- CGR version: 0.19.0
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/cgr/

**Describe the bug (clear and concise)**
The date picker on the search bar in the Explorer module is cut off at the top of the page (see screenshot).

**To Reproduce**
1. As any user, open the Explorer module.
2. Select a date to search a Geo-Object for.

**Expected behavior (clear and concise)**
The full date picker is visible.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/a2b40acd-a2d4-49c7-a83e-6dfd3dd7049e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 100.0.4896.75

**Additional context (if any)**

**Comment by rfromthecastle** [comment] 2022-07-25 03:45
High priority for Laos

**Comment by rrowlands** [comment] 2022-12-21 22:56
I was not able to exactly reproduce the provided screenshot. This is what was happening for me on staging / demo (it was cut off on the left)

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/2299c94c-06c4-4211-9553-af0397dcc377)

With a little tinkering this is the best I can do, which appears to satisfy the requirements of this ticket

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/473c5a35-84c4-4ff1-8dd9-ad0a0d25a320)

committed as e58f4dc052d465d9c7a305eb6b4a357ca0d4f3ea

**Comment by rfromthecastle** [comment] 2023-02-22 02:51
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/6b5d5972-8293-41c8-a764-497a4b787407)
Still seeing the date picker cut off on the left hand side on Staging for me

**Comment by rrowlands** [comment] 2023-02-24 22:31
@rfromthecastle Thanks for the heads up. Looks like some other changes conflicted with my earlier changes. I have addressed this as 9ab973d6059c375038ea322f1d155f77b6f0140a and pushed the fix to staging.

**Comment by rfromthecastle** [comment] 2023-02-27 02:08
![image](https://user-images.githubusercontent.com/18660080/221455547-2ba0e5cc-1885-4583-95b5-1ea1166690aa.png)
Looking good now!

**Comment by justinlewis** [comment] 2023-02-27 02:28
Rica verified fix so closing.

**Closed by justinlewis** 2023-02-27 02:28 UTC
Labels: bug
