### ISSUE TITLE
Refresh button not working on staging

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#719] opened 2022-01-03 23:48 UTC
**List the CGR information**
- CGR version: 0.17.2
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
To test if ticket #628 was implemented I went to the 2021-01-01 instance of the Province master list (MOHA).

As the hierarchy information was not appearing in the list I clicked the refresh button. The window turned grey as per the screenshot below and got stuck there. 

I had to refresh the browser to get back to the list. Once this done the refresh button seemed to work correctly (not stuck on the grey window anymore) except that the parent information is still not appearing in the list while it is definitively in the graph (information appears in the view/edit geo-object modal.

**To Reproduce**
As a RA/RM:
1. Go to the lists module
2. Open the 2021-01-01 exploratory instance of the Province master list (MOHA)
3. Click the refresh button
4. See error 1: the grey window does not close (screenshot below)
5. Refresh the browser
6. Click the refresh button again (see that it is working this time but the hierarchy information is still not appearing
7. Click the edit pen icon in the action column for any of the records
8. Click the hierarchy tab
9. See that there is indeed hierarchy information for the administrative structure hierarchy in the graph

I created a new exploratory list to find out that the hierarchy information is not appearing in the list neither

**Expected behavior (clear and concise)**
The list shows the hierarchy information and the refresh button is working

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/147992029-3c4ef218-b588-45df-af61-7d0ceaa5e8ae.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: latest one

**Additional context (if any)**

**Comment by jsmethie** [comment] 2022-04-14 21:30
Duplicate of #743

**Closed by jsmethie** 2022-04-14 21:30 UTC
