### ISSUE TITLE
Start date can be specified in the future

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#503] opened 2020-12-31 08:54 UTC
**List the CGR information**
- CGR version: 0.13.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
Each time that a start date can be specified (lists, import,...) it is possible to enter a date in the future

**To Reproduce**
As any role:
1. Go to any module where you need to specify a start date
2. Enter a start date in the future
3. See error: the date in question is accepted (See example in screenshot below)

**Expected behavior (clear and concise)**
Start date can only be set in the past or on today's date

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/103402789-c2c11000-4b88-11eb-855d-aaa6eb4304f5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment] 2021-02-19 04:26
Did you mean "Start date can only be set in the **past** or on today's date"?

**Comment by SteeveEbener** [comment] 2021-02-19 04:51
Ooopss...indeed meant in the past or on today's date. I have adjusted the text. Thanks

**Comment by SteeveEbener** [comment] 2021-03-23 05:25
You can still specify a start date in the future in the following modules:
- import module:
![image](https://user-images.githubusercontent.com/12602163/112096718-c9847f80-8bd9-11eb-88d3-765f53bce2db.png)

- Create list:
![image](https://user-images.githubusercontent.com/12602163/112096781-e91ba800-8bd9-11eb-9bb7-114b2bdc3519.png)

- Generate a new exporatory list
![image](https://user-images.githubusercontent.com/12602163/112097038-52032000-8bda-11eb-985e-d96af0492a9f.png)

- Explorer (even if this module remains to be heavily modified)
![image](https://user-images.githubusercontent.com/12602163/112097533-259bd380-8bdb-11eb-9dce-086fbc47200e.png)

The only use case where the change seems to be implemented right now is when you specify a start date in relation to an attribute instance modify or add a new geo-object)

**Comment by justinlewis** [comment] 2021-03-23 16:19
Looks like I misunderstood the HTML spec for the "max" attribute.  It only works with the calendar part of the date picker (vs manual entry). I'll need to add some code to manually prevent this because there is not HTML spec to control future date selection for manual entry. 

![Screenshot from 2021-03-23 10-15-39.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/86ecb3a2-c958-4a78-a12c-faf185628c3d)

**Comment by SteeveEbener** [comment] 2021-05-04 01:34
Just checked under 0.14.6 and you can still manually, or through the calendar, specify an end date in the future in the import module. Once done the start date can sometimes, but not always, also be set in the future as per the following screenshot:
![image](https://user-images.githubusercontent.com/12602163/116951842-8e3a9d80-acbb-11eb-833e-2473212b0299.png)

The other modules are working as expected

**Comment by justinlewis** [comment] 2021-06-05 21:54
@steeveebener - I just tested this on Demo (v0.14.7) and Staging (v0.14.8) and was not able to reproduce. I'm using Chrome browser which I believe you use as well. I'll need to know how you got the date fields to that state in detail. For example, when you entered the date manually did you hit enter or click outside the text input to "set the date"?

**Comment by SteeveEbener** [comment] 2021-06-06 01:49
@justinlewis. I am indeed using Chrome (Version 91.0.4472.77 (Official Build) (64-bit))

Here is how I can set the end date in the future:
1. Enter it manually (ex: 2023-01-01) and hit the enter key:
![image](https://user-images.githubusercontent.com/12602163/120909777-2953d800-c6ab-11eb-8308-b61b3203aac2.png)

2. by clicking on the forward button in the calendar (arrow next to the month and year) and selecting a day:
![image](https://user-images.githubusercontent.com/12602163/120909804-720b9100-c6ab-11eb-81de-46dcfde71e4c.png)

Once you have an end date set in the future you can then also set the start date in the future as well but an error message appears in this case:
![image](https://user-images.githubusercontent.com/12602163/120909869-4f2dac80-c6ac-11eb-809f-b9aa6f385a7c.png)


This being said, if you then change the start date to be in the present or past then you can submit:
![image](https://user-images.githubusercontent.com/12602163/120909876-59e84180-c6ac-11eb-857f-9c4dd3868f2d.png)


=> In conclusion: the issue is with the end date picker. I hope this helps.

**Comment by justinlewis** [comment] 2021-06-15 19:55
@steeveebener If I understand correctly your last comment is highlighting how you can set the end date in the future?

If so that would fall under [#582](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/582). I'll add a reference to this ticket from that one so your workflow above is findable.

**Comment by SteeveEbener** [comment] 2021-06-15 22:53
@justinlewis . Yes, indeed. Thanks for the reference in #582

**Comment by SteeveEbener** [comment] 2021-06-18 09:18
Tested under 0.14.10 and the following is still possible (meaning needing to be fixed:

1. Enter the end date manually (ex: 2023-01-01) and hit the enter key:

![image](https://user-images.githubusercontent.com/12602163/122538040-bf4b1380-d058-11eb-90cf-f44f8e8bba1e.png)
 
2. by clicking on the forward button in the calendar (arrow next to the month and year) and selecting a day:
image

![image](https://user-images.githubusercontent.com/12602163/122538328-03d6af00-d059-11eb-8b72-159d54c673f7.png)

**Comment by justinlewis** [comment] 2021-08-19 20:48
Moving to sprint 0.16.0 to test this last issue @steeveebener found

**Comment by justinlewis** [comment] 2021-10-06 02:12
@SteeveEbener Because #582 covers end dates and this ticket specifically targets start dates the last couple comments you have referring to end dates shouldn't hold back testing/closing of this ticket. There are unique considerations for end dates in the future compared to start dates. I outline this briefly in a comment on ticket #582.

**Closed** 2021-10-06 11:55 UTC
